[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "base64-sol=node_modules/base64-sol",
    "@openzeppelin/contracts/ownership=lib/openzeppelin-contracts/contracts/access"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
